# Pre-commit configuration file based on the `lightning-hydra-template` template one.
# Source: https://github.com/ashleve/lightning-hydra-template

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: trailing-whitespace

  # python code formatting
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [--line-length, "99"]

  # python import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  # python upgrading syntax to newer version
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  #TODO uncomment when fixed for pre-commit 4
  # python docstring formatting
  # - repo: https://github.com/myint/docformatter
  #   rev: v1.7.5
  #   hooks:
  #     - id: docformatter
  #       args:
  #         [
  #           --in-place,
  #           --wrap-summaries=99,
  #           --wrap-descriptions=99,
  #           --style=sphinx,
  #           --black,
  #         ]

  #TODO uncomment later as it will always fail for now
  # python docstring coverage checking
  # - repo: https://github.com/econchick/interrogate
  #   rev: 1.7.0
  #   hooks:
  #     - id: interrogate
  #       args:
  #         [
  #           --verbose,
  #           --fail-under=80,
  #           --ignore-init-module,
  #           --ignore-init-method,
  #           --ignore-module,
  #           --ignore-nested-functions,
  #           --ignore-property-decorators,
  #           --ignore-magic,
  #           -vv,
  #         ]
  #       pass_filenames: false

  # python dead code checking
  - repo: https://github.com/asottile/dead
    rev: v1.5.2
    hooks:
      - id: dead

  # python check (PEP8), programming errors and code complexity
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          [
            "--extend-ignore",
            "E203,E402,E501,F401,F841,RST2,RST301",
            "--exclude",
            "logs/*,data/*",
            "--per-file-ignores",
            "__init__.py:F401,F403",
          ]
        additional_dependencies: [flake8-rst-docstrings==0.3.0]

  # python security linter
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.10"
    hooks:
      - id: bandit
        args: ["-s", "B101,B301"]

  #TODO need to find a new formatter, this one was archived
  # yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types: [yaml]
        exclude: "environment.yaml"

  # shell scripts linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  # md formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.18
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat_frontmatter
          - mdformat-toc
          - mdformat-black

  # word spelling linter
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - --skip=logs/**,data/**,*.ipynb
          - --ignore-words-list=abc,def

  # jupyter notebook linting
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-black
        args: ["--line-length=99"]
      - id: nbqa-isort
        args: ["--profile=black"]
      - id: nbqa-flake8
        args:
          [
            "--extend-ignore=E203,E402,E501,F401,F841",
            "--exclude=logs/*,data/*",
          ]
